### ISSUE TITLE
Starting up the container with existing certs fails

### ISSUE THREAD

**Issue by BrianAdams** [smashwilson/lets-nginx#3]
It you attach volumes that have certs from a previous run and then try running the image, it will fail because the letencrypt-auto, while correctly defaulting to do nothing, has an exit code of 1 which aborts the script and exits the container.

As a work around I have added `|| true` to the command so that it does not fail.  Open to better ideas on how to correct this!

**Comment by smashwilson** [comment]
> It you attach volumes that have certs from a previous run and then try running the image [...]

Yeah, I didn't get that far :wink: Definitely a good idea, though: it'd be best to keep the certs in a data volume container to be available for backups and so on.

> As a work around I have added `|| true` to the command so that it does not fail.

Hmm. I'm not fond of that specific solution because it'll hide any other problems that happen with the script in other cases, like hitting rate limits.

Maybe we could add a conditional to skip the initial `letsencrypt` run if the certificate already exists:

``` bash
if [ -f /var/letsencrypt/live/${DOMAIN}/privkey.pem]; then
  letsencrypt certonly # ...
fi
```

**Comment by marcellodesales** [comment]
@smashwilson @BrianAdams did this work? I'm looking for an nginx solution with SSL termination

**Comment by itzg** [comment]
Hi, I'm working on a modification right now to do this. [An article](https://getcarina.com/blog/weekly-news-docker-sock-letsencrypt/) next to yours, @smashwilson , showed an interesting use of `docker volume` that I wanted to blend in with your image.

**Comment by itzg** [comment]
...I'm also going to have it consult an optional `/cache` location to re-use previous DH params

**Comment by marcellodesales** [comment]
@itzg I'm interested in testing your solution...

**Comment by itzg** [comment]
Thanks @marcellodesales.  If it helps, I added a section to the README capturing the procedure I had used for testing this PR.
